/**
 * Cleans and builds the root TypeScript engine into ignored dist output.
 */
import { rm, mkdir, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";

await rm("dist", { recursive: true, force: true });
const compiler = process.platform === "win32" ? "tsc.cmd" : "tsc";
execFileSync(compiler, ["--project", "tsconfig.json"], { stdio: "inherit" });

// the target manifest CLI: the grand merge folded packager/targetcli.ts
// into distribution.ts (Section 7) whose CLI main only activates when
// argv[1] ends with targetcli.js - the historical entry point that the
// targets workflow invokes. The build regenerates the thin wrapper so
// the contract dist/packager/targetcli.js keeps working (nothing lost).
await mkdir("dist/packager", { recursive: true });
await writeFile(
  "dist/packager/targetcli.js",
  '// generated by tests/scripts/buildengine.mjs - the thin CLI wrapper that\n// activates the target manifest CLI absorbed into distribution.ts\n// (Section 7); its CLI main runs when argv[1] ends with targetcli.js.\nimport "../distribution.js";\n',
);
