[package]
name = "saddle-desktop"
version = "1.8.19"
description = "Saddle desktop browser shell"
authors = ["wenathlan"]
edition = "2021"
license = "GPL-3.0-only"
build = "build.rs"

[lib]
name = "saddle_desktop"
path = "lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "saddle-desktop"
path = "main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
